TestApi/TestApi.Common/Builders/ADUserBuilder.cs
TestApi/TestApi.Common/Builders/AllocateUsersBuilder.cs
TestApi/TestApi.Common/Builders/HearingBuilder.cs
TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Exceptions/ApplicationNotPermittedException.cs
TestApi/TestApi.Common/TestApi.Common.csproj
TestApi/TestApi.Contract/Requests/AllocateUsersRequest.cs
TestApi/TestApi.Contract/TestApi.Contract.csproj
TestApi/TestApi.DAL/Commands/AllocationService.cs
TestApi/TestApi.Domain/Enums/UserType.cs
TestApi/TestApi.Domain/Helpers/UserTypeName.cs
TestApi/TestApi.IntegrationTests/Configuration/ApiUrlFactory.cs
TestApi/TestApi.IntegrationTests/Data/TestData.cs
TestApi/TestApi.IntegrationTests/Data/TestDataManager.cs
TestApi/TestApi.IntegrationTests/Features/AllocationHearing.feature
TestApi/TestApi.IntegrationTests/Steps/AllocationHearingsSteps.cs
TestApi/TestApi.IntegrationTests/Steps/BaseSteps.cs
TestApi/TestApi.IntegrationTests/Steps/HearingSteps.cs
TestApi/TestApi.IntegrationTests/Steps/UserSteps.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocationControllerTestBase.cs
TestApi/TestApi.UnitTests/Controllers/HealthCheckControllerTests.cs
TestApi/TestApi.UnitTests/Mappings/AllocationToDetailsResponseMapperTests.cs
TestApi/TestApi.UnitTests/Mappings/UserToUserDetailsMapperTests.cs
TestApi/TestApi/Controllers/AllocationController.cs
TestApi/TestApi/Mappings/UserDetailsResponseToUserMapper.cs

https://tools.hmcts.net/jira/browse/VIH-6259
- Added an end to end test which will allocate users, create hearing with those users and confirm the hearing (create conference). Next stage is to remove unused endpoints and tests and add lots more unit tests. 
```
[ ] Yes
[X] No
```

VIH-6263 Added end to end test

---

TestApi/TestApi.BQSTests/Subscriber/HearingsSubscriberTests.cs
TestApi/TestApi.Common/Data/DefaultData.cs
TestApi/TestApi.DAL/Commands/AllocateByUserIdCommand.cs
TestApi/TestApi.DAL/Commands/UnallocateByUsernameCommand.cs
TestApi/TestApi.DAL/Queries/GetAllocationByUserIdQuery.cs
TestApi/TestApi.Domain/Allocation.cs
TestApi/TestApi.Domain/Helpers/AppShortName.cs
TestApi/TestApi.IntegrationTests/Controllers/Users/GetUserExistsInAdTests.cs
TestApi/TestApi.Tests.Common/Configuration/ApiUrlFactory.cs
TestApi/TestApi.Tests.Common/Configuration/Tokens.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/UnallocateUsersControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Users/DeleteAadUserControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Users/GetTestApiUserByUsernameControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Users/GetUserExistsInAdControllerTests.cs
TestApi/TestApi.UnitTests/Mappings/AllocationToDetailsResponseMapperTests.cs
TestApi/TestApi/Controllers/UserController.cs

https://tools.hmcts.net/jira/browse/VIH-6321
- Replicated all test api calls from admin web
```
[ ] Yes
[X] No
```

VIH-6321 : Replicate all admin web api calls

---

TestApi/TestApi.Services/Clients/UserApiClient.cs
TestApi/TestApi.Services/Contracts/UserApiService.cs

- https://tools.hmcts.net/jira/browse/VIH-6424
- User setup changes for dynamically created test users
```
[ ] Yes
[X] No
```

VIH-6424 No reset for test users

---

TestApi/TestApi.Common/Builders/AllocateUsersRequestBuilder.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.UnitTests/Validations/AllocateUsersValidationTests.cs
TestApi/TestApi/Validations/AllocateUsersRequestValidator.cs

- Either assign case admin or VHO to request
```
[ ] Yes
[X] No
```

VIH-5255 Either assign case admin or VHO to request

---

TestApi/TestApi.Services/Contracts/UserApiService.cs

- Added a retry on the check user exists to handle internal server errors only
```
[ ] Yes
[X] No
```

VIH-5255 Implement retry for check user exists in AD exception

---

TestApi/TestApi.Services/Contracts/UserApiService.cs

- Added null checks to determine non transformed values
```
[ ] Yes
[X] No
```

VIH-5255 Added null checks to determine non transformed values

---

TestApi/TestApi.Common/Configuration/UserGroupsConfiguration.cs
TestApi/TestApi.Common/Data/GroupData.cs
TestApi/TestApi.Services/Contracts/UserApiService.cs
TestApi/TestApi.Services/Helpers/ConvertGroupsStringToList.cs
TestApi/TestApi.Services/Helpers/UserGroups.cs
TestApi/TestApi.UnitTests/Services/ServicesTestBase.cs
azure-pipelines.release.yml
azure-pipelines.yml

- Fixed pipeline secrets issue
```
[ ] Yes
[X] No
```

VIH-5255 Fixed secrets issue

---

CODEOWNERS
azure-pipelines.release.yml
azure-pipelines.yml

- Add secret to yml
```
[ ] Yes
[x] No
```

VIH-5255 Add secret to yml

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Data/AdminWebJudgeData.cs
TestApi/TestApi.DAL/Commands/AllocationService.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs

- Added logic to always reuse the admin web dropdown judge user
```
[ ] Yes
[X] No
```

VIH-6268 Add logic for admin web judge user

---

TestApi/TestApi.DAL/Commands/AllocationService.cs

- Fix for user issue
```
[ ] Yes
[X] No
```

VIH-6268 Fix for admin web test user issue

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Data/AdminWebJudgeData.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.Tests.Common/Verify.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateSingleUserTests.cs

- Added admin web judge user tests
```
[ ] Yes
[X] No
```

VIH-5255 admin web judge user tests

---

TestApi/TestApi.Common/Data/UserData.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Tests.Common/Configuration/ApiUrlFactory.cs
TestApi/TestApi/Controllers/UserController.cs

https://tools.hmcts.net/jira/browse/VIH-6268
- Change default organisation for admin web users
- Fixed username update bug
```
[ ] Yes
[X] No
```

VIH-6268 Change default organisation for admin web users

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Data/HearingData.cs
TestApi/TestApi.Common/Data/UserData.cs
TestApi/TestApi.Domain/Enums/TestType.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateConferenceTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/CreateConferenceControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Hearings/CreateHearingControllerTests.cs
TestApi/TestApi.UnitTests/Services/NewUserAllocationServiceTests.cs

https://tools.hmcts.net/jira/browse/VIH-6509
- Add the ability to create ITHC users with the test api
```
[ ] Yes
[X] No
```

VIH-6509 : Add the ability to create ITHC users with the test api

---

TestApi/TestApi.IntegrationTests/Controllers/Users/RefreshJudgesCacheTests.cs
TestApi/TestApi.Services/Clients/UserApiClient.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Tests.Common/Configuration/ApiUrlFactory.cs
TestApi/TestApi.UnitTests/Controllers/Users/RefreshJudgesCacheTests.cs
TestApi/TestApi/Controllers/UserController.cs

https://tools.hmcts.net/jira/browse/VIH-6510
- Added a refresh judge cache endpoint to the test api
```
[ ] Yes
[X] No
```

VIH-6268 Added refresh judge endpoint to test api

---

README.md

https://tools.hmcts.net/jira/browse/VIH-6320
- Add project readme
```
[ ] Yes
[x] No
```

VIH-6320 Update README.md

---

TestApi/TestApi.BQSTests/Subscriber/HearingsSubscriberTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/GetAudioRecordingLinksTests.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Tests.Common/Configuration/ApiUrlFactory.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/GetAudioRecordingLinkControllerTests.cs
TestApi/TestApi/Controllers/ConferencesController.cs

https://tools.hmcts.net/jira/browse/VIH-6232
- Updated endpoint
```
[ ] Yes
[X] No
```

VIH-6232 updated audio recording links endpoint

---

TestApi/TestApi.DAL/Commands/AllocationService.cs
TestApi/TestApi.DAL/Queries/GetAllUsersByFilterQuery.cs
TestApi/TestApi.IntegrationTests/Database/Queries/GetAllUsersByFilterQueryTests.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Clients/UserApiClient.cs
TestApi/TestApi.UnitTests/Services/ExistingUserAllocationServiceTests.cs
TestApi/TestApi.UnitTests/Services/NewUserAllocationServiceTests.cs

- Fox for test type allocation issues
```
[ ] Yes
[X] No
```

VIH-5255 Fix for test type allocation issues

---

.gitignore
TestApi/TestApi.UnitTests/.config/dotnet-tools.json
TestApi/TestApi.UnitTests/Controllers/Allocations/UnallocateUsersControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/DeleteConferenceControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Hearings/DeleteHearingControllerTests.cs
TestApi/TestApi.UnitTests/stryker-config.json
TestApi/TestApi/Validations/EmailValidator.cs

https://tools.hmcts.net/jira/browse/VIH-6513
> Added Stryker mutation test
```
[ ] Yes
[x] No
```

VIH-6513 Added stryker

---

azure-pipelines.release.yml
azure-pipelines.yml

VIH-6594
update endpoint connection
```
[ ] Yes
[x] No
```

VIH-6594 update endpoint connection

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Domain/Enums/UserType.cs
TestApi/TestApi.Domain/Helpers/UserTypeName.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateUsersTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/ConferencesTestsBase.cs
TestApi/TestApi.Services/Builders/Requests/BookConferenceParticipantsBuilder.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Services/Helpers/UserGroups.cs
TestApi/TestApi.UnitTests/Services/UserApiServiceTests.cs

https://tools.hmcts.net/jira/browse/VIH-6420
- Added Winger UserType
```
[ ] Yes
[X] No
```

VIH-6420 Added Winger UserType

---

TestApi/TestApi.Common/Builders/HearingBuilder.cs
TestApi/TestApi.Common/Data/HearingData.cs
TestApi/TestApi.Common/Data/RoleData.cs
TestApi/TestApi.Contract/Requests/CreateHearingRequest.cs
TestApi/TestApi.IntegrationTests/Controllers/AllocateEndToEndTest.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/ConferencesTestsBase.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateConferenceTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/HearingsTestsBase.cs
TestApi/TestApi.Services/Builders/Requests/BookConferenceParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookConferenceRequestBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.Tests.Common/Verify.cs
TestApi/TestApi.UnitTests/Validations/CreateHearingValidationTests.cs
TestApi/TestApi/Validations/CreateHearingRequestValidator.cs

https://tools.hmcts.net/jira/browse/VIH-6420
- Added case role for wingers and tests
```
[ ] Yes
[X] No
```

VIH-6420 case role for wingers

---

TestApi/TestApi.Services/Builders/Requests/BookConferenceParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-6623
- Allow any number of individuals and reps
```
[ ] Yes
[X] No
```

VIH-6623 Allow any number of individuals and reps

---

TestApi/TestApi.BQSTests/Subscriber/ParticipantSubscriberTests.cs
TestApi/TestApi.Common/Data/UserData.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Responses/HearingDetailsResponseBuilder.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Tests.Common/Verify.cs

https://tools.hmcts.net/jira/browse/VIH-6527
- Removed reference from hearing builders
```
[ ] Yes
[X] No
```

VIH-6527 Removed Reference

---

TestApi/TestApi.Common/Data/RoleData.cs

https://tools.hmcts.net/jira/browse/VIH-6643
- Change hearing role names
```
[ ] Yes
[X] No
```

VIH-6643 Change hearing role names

---

TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs

https://tools.hmcts.net/jira/browse/VIH-6570
Updated video-api client
```
[ ] Yes
[ ] No
```

VIH-6570 Updated video api client

---

TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Tests.Common/Configuration/ApiUrlFactory.cs
TestApi/TestApi/Controllers/HealthController.cs
TestApi/TestApi/Controllers/HearingsController.cs

- Renamed endpoints
```
[ ] Yes
[X] No
```

VIH-6690 Renamed endpoints

---

TestApi/TestApi.Common/Configuration/UserGroupsConfiguration.cs
TestApi/TestApi.Common/Data/GroupData.cs
TestApi/TestApi.Domain/Enums/Application.cs
TestApi/TestApi.Domain/Enums/UserType.cs
TestApi/TestApi.Domain/Helpers/AppShortName.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.IntegrationTests/Test/TestContext.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Services/Helpers/UserGroups.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.UnitTests/Services/ServicesTestBase.cs
azure-pipelines.release.yml
azure-pipelines.yml

- Add Test Web front end test automation users
```
[ ] Yes
[X] No
```

VIH-6627 Add Test Web front end test automation users

---

TestApi/TestApi.Common/Configuration/UserGroupsConfiguration.cs
TestApi/TestApi.Common/Data/GroupData.cs
TestApi/TestApi.Services/Helpers/UserGroups.cs
TestApi/TestApi.UnitTests/Services/ServicesTestBase.cs
azure-pipelines.release.yml
azure-pipelines.yml

- added JOH ad group for new users
```
[ ] Yes
[X] No
```

VIH-6663 added JOH ad group for new users

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Data/HearingData.cs
TestApi/TestApi.Common/Data/UserData.cs
TestApi/TestApi.Common/TestApi.Common.csproj
TestApi/TestApi.Common/packages.lock.json
TestApi/TestApi.DAL/Migrations/TestApiDbContextModelSnapshot.cs
TestApi/TestApi.DAL/TestApi.DAL.csproj
TestApi/TestApi.DAL/packages.lock.json
TestApi/TestApi.Domain/Enums/TestType.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateUsersTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateConferenceTests.cs
TestApi/TestApi.IntegrationTests/TestApi.IntegrationTests.csproj
TestApi/TestApi.IntegrationTests/packages.lock.json
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/CreateConferenceControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Hearings/CreateHearingControllerTests.cs
TestApi/TestApi.UnitTests/Services/ExistingUserAllocationServiceTests.cs
TestApi/TestApi.UnitTests/packages.lock.json
TestApi/TestApi/TestApi.csproj
TestApi/TestApi/packages.lock.json

- Add Demo Test Type
```
[ ] Yes
[X] No
```

VIH-6690 Add Demo Test Type

---

TestApi/TestApi.IntegrationTests/Controllers/Users/ResetUserPasswordTests.cs
TestApi/TestApi.UnitTests/Validations/ResetPasswordValidationTests.cs
TestApi/TestApi/Validations/ResetPasswordRequestValidator.cs

- Prevent Automation User Password Reset
```
[ ] Yes
[X] No
```

VIH-5255 Prevent Automation User Password Reset

---

TestApi/TestApi.Common/Data/UserData.cs
TestApi/TestApi.Services/Builders/Requests/UpdateBookingRequestBuilder.cs

- Add a default updated by
```
[ ] Yes
[X] No
```

VIH-5255 Add a default updated by

---

TestApi/TestApi.Common/Builders/AllocateUserRequestBuilder.cs
TestApi/TestApi.Common/Builders/HearingBuilder.cs
TestApi/TestApi.Common/Data/EmailData.cs
TestApi/TestApi.Common/Data/HearingData.cs
TestApi/TestApi.Contract/Requests/AllocateUserRequest.cs
TestApi/TestApi.Contract/Requests/CreateHearingRequest.cs
TestApi/TestApi.Contract/Responses/AllocationDetailsResponse.cs
TestApi/TestApi.DAL/Commands/AllocateByUserIdCommand.cs
TestApi/TestApi.DAL/Commands/AllocationService.cs
TestApi/TestApi.DAL/Mappings/AllocationMap.cs
TestApi/TestApi.DAL/Migrations/20210108151220_AllocatedBy.Designer.cs
TestApi/TestApi.DAL/Migrations/20210108151220_AllocatedBy.cs
TestApi/TestApi.DAL/Queries/GetAllAllocationsForAUserQuery.cs
TestApi/TestApi.DAL/Queries/GetAllocatedUserByUserTypeQuery.cs
TestApi/TestApi.Domain/Allocation.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/GetAllocationsByUserTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateVideoEventTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.IntegrationTests/Database/Queries/GetAllocatedUserByUserTypeQueryTests.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.Tests.Common/Configuration/ApiUrlFactory.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/GetAllAllocationsByUserTests.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/CreateVideoEventControllerTests.cs
TestApi/TestApi.UnitTests/Services/NewUserAllocationServiceTests.cs
TestApi/TestApi.UnitTests/Services/ServicesTestBase.cs
TestApi/TestApi/Controllers/AllocationController.cs
TestApi/TestApi/Mappings/AllocationToDetailsResponseMapper.cs

https://tools.hmcts.net/jira/browse/VIH-6961
https://tools.hmcts.net/jira/browse/VIH-6950
- Added allocated by to domain
- Added endpoint to get all allocations by username
- Added endpoints to create hearings
```
[ ] Yes
[X] No
```

VIH-6961 Added allocated by

---

TestApi/TestApi.DAL/Queries/GetAllAllocationsForAUserQuery.cs

- Fixed get allocations bug
```
[ ] Yes
[X] No
```

VIH-5255 Fixed get allocations bug

---

TestApi/TestApi.Common/Builders/AllocateUserRequestBuilder.cs
TestApi/TestApi.Common/Data/HearingData.cs
TestApi/TestApi.Contract/Requests/AllocateUsersRequest.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/ConferencesTestsBase.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateConferenceTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/HearingsTestsBase.cs
TestApi/TestApi.Services/Builders/Requests/BookConferenceParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Tests.Common/Verify.cs
TestApi/TestApi/Controllers/AllocationController.cs

https://tools.hmcts.net/jira/browse/VIH-6972
- Added allocatedBy to allocate users request
- Fixed a bug with more reps than individuals
- Added tests for the bug
```
[ ] Yes
[X] No
```

VIH-6972 Added allocatedby to allocate users request

---

TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.UnitTests/Validations/AllocateUserValidationTests.cs
TestApi/TestApi.UnitTests/Validations/AllocateUsersValidationTests.cs
TestApi/TestApi/Validations/AllocateUserRequestValidator.cs
TestApi/TestApi/Validations/AllocateUsersRequestValidator.cs

https://tools.hmcts.net/jira/browse/VIH-6992
- Extend the allowable time to allocate a user
```
[ ] Yes
[X] No
```

VIH-6992 Extend the allowable time to allocate a user

---

TestApi/TestApi.Contract/Requests/CreateHearingRequest.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs

https://tools.hmcts.net/jira/browse/VIH-6993
- Allow custom case name prefixes
```
[ ] Yes
[X] No
```

VIH-6993 Allow custom case name prefixes

---

TestApi/TestApi.IntegrationTests/Controllers/Conferences/ConferencesTestsBase.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateEventTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/GetTasksTests.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/CreateEventControllerTests.cs
TestApi/TestApi/Controllers/ConferencesController.cs

https://tools.hmcts.net/jira/browse/VIH-6879
- To reflect event changes
```
[ ] Yes
[X] No
```

VIH-6879 Updated with event changes

---

TestApi/TestApi.Common/Data/UserData.cs
TestApi/TestApi.Contract/Requests/CreateHearingRequest.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.UnitTests/Controllers/Hearings/ConfirmHearingsControllerTests.cs

https://tools.hmcts.net/jira/browse/VIH-7009
- Added Created By to hearing request
```
[ ] Yes
[X] No
```

VIH-7009 Added Created By to hearing request

---

TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs

https://tools.hmcts.net/jira/browse/VIH-7014
- Removed app name for all but non auto tests
```
[ ] Yes
[X] No
```

VIH-7014 Removed app name for all but non auto tests

---

TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateUsersTests.cs
TestApi/TestApi/Controllers/AllocationController.cs

https://tools.hmcts.net/jira/browse/VIH-7057
- Implement parallel execution locking
```
[ ] Yes
[X] No
```

VIH-7057 Implement parallel execution locking

---

TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Services/Services/VideoApiService.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/GetConferenceByHearingRefIdControllerTests.cs
TestApi/TestApi/Controllers/ConferencesController.cs

- Updated clients
```
[ ] Yes
[X] No
```

VIH-6162 Updated clients

---

azure-pipelines.release.yml

- Added test3 env
```
[ ] Yes
[X] No
```

VIH-5552 Added test3 env

---

TestApi/TestApi.AcceptanceTests/Controllers/HearingTests.cs
TestApi/TestApi.AcceptanceTests/Controllers/TestsBase.cs
TestApi/TestApi.AcceptanceTests/Helpers/Setup.cs
TestApi/TestApi.AcceptanceTests/Helpers/TestContext.cs
TestApi/TestApi.AcceptanceTests/Helpers/TestData.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.Services/Services/VideoApiService.cs
TestApi/TestApi/Controllers/ConferencesController.cs

- Added extra AC tests
```
[ ] Yes
[X] No
```

VIH-7151 Added extra AC tests

---

TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi/Controllers/AllocationController.cs

- attempt to fix user allocation lock
```
[ ] Yes
[X] No
```

VIH-5552 fix to allocation lock

---

GitVersion.yml

Fixing issue identified by James
<GetApplicationVersion>b__6_0(AssemblyFileVersionAttribute a) in /src/TestApi/Controllers/HealthController.cs:line 109
at TestApi.Controllers.HealthController.GetExecutingAssemblyAttribute[T](Func`2 value) in /src/TestApi/Controllers/HealthController.cs:line 118
at TestApi.Controllers.HealthController.GetApplicationVersion() in /src/TestApi/Controllers/HealthController.cs:line 107
at TestApi.Controllers.HealthController.HealthAsync() in /src/TestApi/Controllers/HealthController.cs:line 48
```
[ ] Yes
[X] No
```

added GitVersion

---

TestApi/TestApi.Common/Data/EmailData.cs
TestApi/TestApi.Common/Data/HearingData.cs
TestApi/TestApi.Common/Data/RoleData.cs
TestApi/TestApi.IntegrationTests/Controllers/Hearings/CreateHearingTests.cs
TestApi/TestApi.Services/Clients/BookingsApiClient.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/UnallocateUsersControllerTests.cs
TestApi/TestApi.UnitTests/Controllers/Users/DeleteAadUserControllerTests.cs
TestApi/TestApi.UnitTests/Validations/UnallocateUsersValidationTests.cs
TestApi/TestApi/Controllers/HearingsController.cs

https://tools.hmcts.net/jira/browse/VIH-7305
- Update emails and case type Generic
```
[ ] Yes
[X] No
```

VIH-7305 Update emails and case type Generic

---

TestApi/TestApi.Common/Builders/UserBuilder.cs

-  Fix Last Name Issue
```
[ ] Yes
[X] No
```

VIH-5552 Fix Last Name Issue

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Configuration/UserGroupsConfiguration.cs
TestApi/TestApi.Common/Data/GroupData.cs
TestApi/TestApi.Common/Data/RoomData.cs
TestApi/TestApi.Domain/Enums/UserType.cs
TestApi/TestApi.IntegrationTests/Controllers/AllocateEndToEndTest.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateUsersTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/ConferencesTestsBase.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/CreateEventTests.cs
TestApi/TestApi.Services/Builders/Requests/BookConferenceParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/ConferenceEventRequestBuilder.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.Services/Helpers/UserGroups.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateUsersTests.cs
TestApi/TestApi.UnitTests/Controllers/Conferences/CreateEventControllerTests.cs
TestApi/TestApi.UnitTests/Services/ServicesTestBase.cs
TestApi/TestApi.UnitTests/Services/UserApiService/AddUserToGroupsServiceTests.cs
TestApi/TestApi.UnitTests/Services/UserApiService/CreateNewUserServiceTests.cs
TestApi/TestApi/TestApi.csproj
azure-pipelines.release.yml
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-7344
-  Add Witnesses
```
[ ] Yes
[X] No
```

VIH-7344 Add Witnesses

---

TestApi/TestApi.Common/Builders/UserBuilder.cs
TestApi/TestApi.Common/Configuration/UserGroupsConfiguration.cs
TestApi/TestApi.Common/Data/GroupData.cs
TestApi/TestApi.Domain/Enums/UserType.cs
TestApi/TestApi.IntegrationTests/Controllers/AllocateEndToEndTest.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Allocations/AllocateUsersTests.cs
TestApi/TestApi.IntegrationTests/Controllers/Conferences/ConferencesTestsBase.cs
TestApi/TestApi.Services/Builders/Requests/BookConferenceParticipantsBuilder.cs
TestApi/TestApi.Services/Builders/Requests/BookHearingParticipantsBuilder.cs
TestApi/TestApi.Services/Helpers/UserGroups.cs
TestApi/TestApi.UnitTests/Controllers/Allocations/AllocateSingleUserTests.cs
TestApi/TestApi.UnitTests/Services/ServicesTestBase.cs
TestApi/TestApi.UnitTests/Services/UserApiService/AddUserToGroupsServiceTests.cs
TestApi/TestApi.UnitTests/Services/UserApiService/CreateNewUserServiceTests.cs
azure-pipelines.release.yml
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-7346
- Added Interpreter
```
[ ] Yes
[X] No
```

VIH-7346 Add Interpreter

---

TestApi/TestApi.Services/Builders/Requests/BookHearingRequestBuilder.cs
TestApi/TestApi.Services/Clients/VideoApiClient.cs
TestApi/TestApi.UnitTests/Validations/CreateHearingValidationTests.cs
TestApi/TestApi/Validations/CreateHearingRequestValidator.cs

- Fixes for interpreter as linked participants 
```
[ ] Yes
[X] No
```

VIH-5552 Fixes for interpreter as linked participants

---

TestApi/TestApi.AcceptanceTests/packages.lock.json
TestApi/TestApi.Client/TestApi.Client.csproj
TestApi/TestApi.DAL/packages.lock.json
TestApi/TestApi.IntegrationTests/packages.lock.json
TestApi/TestApi.Services/TestApi.Services.csproj
TestApi/TestApi.UnitTests/packages.lock.json
TestApi/TestApi/packages.lock.json

- Update to latest API packages
```
[ ] Yes
[X] No
```

VIH-5552 Update to API packages

---

TestApi/TestApi.AcceptanceTests/packages.lock.json
TestApi/TestApi.Client/TestApi.Client.csproj
TestApi/TestApi.DAL/TestApi.DAL.csproj
TestApi/TestApi.DAL/packages.lock.json
TestApi/TestApi.IntegrationTests/packages.lock.json
TestApi/TestApi.Services/TestApi.Services.csproj
TestApi/TestApi.UnitTests/Controllers/Conferences/GetConferencesForTodayVhoControllerTests.cs
TestApi/TestApi.UnitTests/packages.lock.json
TestApi/TestApi/Controllers/ConferencesController.cs
TestApi/TestApi/packages.lock.json
TestApi/nuget.config

VIH-7880
Update nuget package version
```
[ ] Yes
[x] No
```

VIH-7880 Update nuget

---

TestApi/TestApi.AcceptanceTests/TestApi.AcceptanceTests.csproj
TestApi/TestApi.AcceptanceTests/packages.lock.json

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
https://tools.hmcts.net/jira/browse/VIH-8670
Update to the latest nuget packages and project changes
```
[ ] Yes
[ ] No
```

VIH-8670 - nuget and project updates

---

TestApi/TestApi.AcceptanceTests/TestApi.AcceptanceTests.csproj
TestApi/TestApi.AcceptanceTests/packages.lock.json
TestApi/TestApi.Client/TestApi.Client.csproj
TestApi/TestApi.Common/TestApi.Common.csproj
TestApi/TestApi.Common/packages.lock.json
TestApi/TestApi.DAL/TestApi.DAL.csproj
TestApi/TestApi.DAL/packages.lock.json
TestApi/TestApi.IntegrationTests/TestApi.IntegrationTests.csproj
TestApi/TestApi.IntegrationTests/packages.lock.json
TestApi/TestApi.Services/TestApi.Services.csproj
TestApi/TestApi.UnitTests/TestApi.UnitTests.csproj
TestApi/TestApi.UnitTests/packages.lock.json
TestApi/TestApi/packages.lock.json

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

VIH-8349 - Update Dependencies

---

TestApi/TestApi.AcceptanceTests/TestApi.AcceptanceTests.csproj
TestApi/TestApi.AcceptanceTests/packages.lock.json
TestApi/TestApi.Client/TestApi.Client.csproj
TestApi/TestApi.Common/TestApi.Common.csproj
TestApi/TestApi.Common/packages.lock.json
TestApi/TestApi.DAL/TestApi.DAL.csproj
TestApi/TestApi.DAL/packages.lock.json
TestApi/TestApi.IntegrationTests/TestApi.IntegrationTests.csproj
TestApi/TestApi.IntegrationTests/packages.lock.json
TestApi/TestApi.Services/Services/BookingsApiService.cs
TestApi/TestApi.Services/TestApi.Services.csproj
TestApi/TestApi.UnitTests/Controllers/Hearings/GetAllHearingsByDefaultCaseTypeControllerTests.cs
TestApi/TestApi.UnitTests/packages.lock.json
TestApi/TestApi/Controllers/HearingsController.cs
TestApi/TestApi/packages.lock.json

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

VIH-9130 Updated nuget dependencies and out of date implementations

---

azure-pipelines.sds.pr-close.yml
azure-pipelines.sds.pr-release.yml
azure-pipelines.sds.release.yml
charts/vh-test-api/Chart.yaml
charts/vh-test-api/values.demo.template.yaml
charts/vh-test-api/values.dev.template.yaml

VIH-9999 - Patch

---

azure-pipelines.sds.pr-release.yml
azure-pipelines.sds.release.yml

VIH-9241
Add Conditions 
```
[ ] Yes
[ x ] No
```

VIH-9241 - Add Conditions 

---

TestApi/TestApi/Dockerfile

https://tools.hmcts.net/jira/browse/VIH-9477
VIH-9477 Add curl to docker build
```
[ ] Yes
[X ] No
```

VIH-9477 Add curl to docker build

---

azure-pipelines.sds.master-release.yml
azure-pipelines.sds.release.yml

https://tools.hmcts.net/jira/browse/VIH-9650?filter=-1
Remove Test Environment from SDS.
```
[ ] Yes
[X ] No
```

VIH-9650 removing test environment from sds

---

azure-pipelines.sds.release.yml
variables/demo.yaml

https://tools.hmcts.net/jira/browse/VIH-9642
HMCTS have asked for the Demo environment for VH to be recreated.
This environment is to be used strictly for Demos and will have a copy of Production releases.
1. Create Demo Infra via Terraform (Core & Wowza) 
2. Amend DNS 
3. Configure AFD
4. Add Flux Configuration 
5. Amend Release Pipelines to Run EF in Demo
```
[ ] Yes
[X ] No
```

VIH-9642 Create Demo Environment in SDS

---

azure-pipelines.sds.master-release.yml
azure-pipelines.sds.pr-release.yml

https://tools.hmcts.net/jira/browse/DTSPO-12091
Fix master release pipeline
```
[ ] Yes
[x] No
```

VIH-0000 - Update master release pipeline
